djangonaut-space/wagtail-indymeet

home/templates/home/event_detail.html
home/templates/home/includes/session_card.html
home/templates/home/prerelease/session_detail.html

* Respect the linebreaks in the session description
* Limit the number of words on the cards for sessions.
* Update event detail view to have line breaks on the description and to urlize links.

Fix home templates

---

home/templates/home/home_page.html

Want to verify our website against our Mastodon account. It might be this simple 🤷‍♀️ 
https://indieweb.social/settings/verification
Verifying your identity on Mastodon is for everyone. Based on open web standards, now and forever free. All you need is a personal website that people recognize you by. When you link to this website from your profile, we will check that the website links back to your profile and show a visual indicator on it.
HERE'S HOW
Copy and paste the code below into the HTML of your website. Then add the address of your website into one of the extra fields on your profile from the "Edit profile" tab and save changes.
`<a rel="me" href="https://indieweb.social/@djangonaut">Mastodon</a>`
Tip: The link on your website can be invisible. The important part is rel="me" which …

Verify our identity on Mastodon by adding rel="me" to Mastodon link.

---

requirements/requirements-dev.txt

The toolbar and django-extensions are already in requirements.txt flake8 and black are managed by pre-commit and not required.

Clean up development requirements file.

---

home/models.py
home/templates/home/prerelease/event_detail.html
home/templates/home/prerelease/event_list.html
home/templates/home/prerelease/session_detail.html
home/tests/test_event_views.py
home/tests/test_session_views.py

Improve the session and event pages (mostly around timezone stuff)

---

.github/workflows/develop_djangonaut_space.yml
.github/workflows/main_djangonaut-space.yml
indymeet/settings/base.py
indymeet/settings/production.py
indymeet/settings/storages.py
package.json
scripts/postbuild.sh

This stops using collectstatic as a part of the oryx build system and uses a custom post build script.
Since tailwind requires node to compile the final css file, we need to add a package.json file and ENABLE_MULTIPLEPLATFORM_BUILD to get Oryx to install both python and node. This allows the post build script to run.
This also fixes the Azure media/static file storage issue by exposing the environment variables to actually push content there.
This will need a few new secrets configured and we may potentially need to change AZURE_CUSTOM_DOMAIN since I don't think that was ever used/tested.

This should allow tailwind to be built.

---

home/templates/home/home_page.html
indymeet/templates/includes/nav.html

Weird daisy chain of errors. I'll have to add it back on my linux machine. 
Wagtail menu requires pillow-heif which has odd installation requirements on windows machine. I'm going back to @tim-schilling 's solution. 
https://wagtailmenus.readthedocs.io/en/stable/installation.html
https://pillow-heif.readthedocs.io/en/latest/installation.html#windows

revert back Blog link! can't test on Windows with new requirements

---

home/templates/home/home_page.html
theme/static_src/src/djangonaut-space.css

The class on the homepage was the bootstrap one, and add also margin on top and bottom of the buttons to avoid them all being stuck together and center the text 
Screenshots 📷

Fix landing page

---

.gitignore
README.md
indymeet/settings/base.py

This documents how to create a fixture for the application. This will make it easier for folks to share reproducible environments locally and avoid needing to rely on staging so heavily.
@dawnwages this also adds the database environment variable to the settings which should restore your local environment.
@sabderemane @RachellCalhoun @dawnwages here's a fixture to use that has the first draft of Rachell's blog post that's on production. Or at least some version of it.
[fixture-20231230.zip](https://github.com/djangonaut-space/wagtail-indymeet/files/13798670/fixture-20231230.zip)

Document how to create/load fixture data

---

.env.template
indymeet/settings/base.py
indymeet/urls.py

The django debug toolbar should not be run in a production environment and should only be enabled in remove environments temporarily. It can expose sensitive information and if we're using a clone of the production data in a staging environment, it could expose prod data.
References #146

Programatically enable the debug toolbar.

---

.github/workflows/tests.yml
indymeet/settings/test.py
manage.py
requirements/requirements-dev.txt
theme/static/README

The production build process requires that this directory exists. Otherwise Django raises a warning in the check system.
I chose to use a README instead of .gitkeep or .gitignore since I could explain the reasoning for the file and folder.

Create a README to always force the theme static dir.

---

indymeet/templates/puput/base.html

This uses the same split, 75-25 for medium screens and up. But now when the browser is smaller, it'll be a single 100% column for both the blog and side content. This will stack the blog.
References #158
Fixes #199
---
---
---

Use grid for the blog page.

---

home/models.py

This addresses the following warning:
> RemovedInWagtail50Warning: ImageChooserPanel is no longer required for image choosers, and should be replaced by FieldPanel. ImageChooserPanel will be removed in a future release. See https://docs.wagtail.org/en/stable/releases/3.0.html#removal-of-special-purpose-field-panel-types

Replace deprecated panel classes with FieldPanel.

---

.env.template.local
.github/workflows/tests.yml
.pytest.ini
README.md
accounts/management/commands/create_playwright_user.py
accounts/management/commands/tests/test_create_playwright_user.py
accounts/tests.py
requirements/requirements-dev.txt
requirements/requirements-test.in
requirements/requirements-test.txt
scripts/local.sh
setup.cfg
tests/__init__.py
tests/conftest.py
tests/test_end_to_end.py

This adds two tests:
- Smoke test of web app
- Smoke test of wagtail application
This also adds a local.sh helper script to run runserver and tailwind start in one file. It's not usable by windows folks, but it should provide a guide to implementing one for windows.
The testing auth flow is to have a predefined username and password for the playwright testing user. This means if you want to run the smoke tests against production locally, you'll need the password for the production playwright user. This is a bit risky considering the test user has Editor permissions to access the wagtail admin.

Add basic playwright test

---

README.md

We can use this URL to create production release PRs: https://github.com/djangonaut-space/wagtail-indymeet/compare/main...develop?title=Production%20Release%20-%20&body=PRs:%0A-%20
A PR template would be used for the develop branch PRs and that's not what we want.

Document production release process

---

indymeet/settings/base.py

Sentry should be helping with this, but I'm still running into application errors that don't make their way to Sentry.

Log all errors and above to the console

---

scripts/postbuild.sh

This would require us to have the database connection settings in our github repository and that doesn't sit well with me currently. Let's keep looking.

Remove migrate from postbuild script.

---

indymeet/templates/blocks/left-image-right-text.html
indymeet/templates/blocks/quote-block.html
indymeet/templates/blocks/quote-left-image.html
indymeet/templates/blocks/rich_text.html
indymeet/templates/blocks/right-image-left-text.html
indymeet/templates/blocks/text-image-heading.html
indymeet/templates/blocks/text-with-heading-left-image.html
indymeet/templates/blocks/text-with-heading-right-image.html
indymeet/templates/blocks/text-with-heading.html

Prior to this changes, the class prose was setting
a specific width and break the responsiveness with the blog container.
This change also add the class
`text-right` in order to align the text on the right side when the image is on the right class
Note: I didn't fully tested it, I haven't finished to configured again my setup

Fix formatting issue on blog post

---

indymeet/templates/blocks/left-image-right-text.html
indymeet/templates/blocks/right-image-left-text.html
indymeet/templates/blocks/text-image-heading.html
indymeet/templates/blocks/text-with-heading-left-image.html
indymeet/templates/blocks/text-with-heading-right-image.html
indymeet/templates/blocks/text-with-heading.html

384 add linebreaks to text

---

home/templates/home/general_page.html
home/templates/home/includes/session_card.html
home/templates/home/prerelease/event_detail.html
home/templates/home/prerelease/event_list.html
home/templates/home/prerelease/session_detail.html
indymeet/templates/base.html
indymeet/templates/includes/nav.html
indymeet/templates/puput/entry_page.html

375 Center Event and Session Detail View

---

indymeet/templates/blocks/rich_text.html

The richtext blocks should handle formatting the links which will result in a tags. This is why we need the `|safe` template filter.

Avoid urlizing richtext fields

---

indymeet/templates/base.html
indymeet/templates/includes/footer.html

Updated the footer to be a sticky one as requested 
* #388

Feat: sticky footer

---

home/templates/home/general_page.html
indymeet/templates/base.html
indymeet/templates/puput/base.html
indymeet/templates/puput/blog_page.html
indymeet/templates/puput/entry_page.html

I removed fontawesome old reference from Puput.
Updated icons inside the blog
I also found 'user' and 'calendar' icons, but I wasn't able to update them because they're probably used inside the Wagtail.
This should fix #445

Fixed social icons inside blog

---

home/admin.py

Add `UserQuestionResponse` and `UserSurveyResponse` in `home/admin.py`
Closes #332

Register UserQuestionResponse and UserSurveyResponse in the admin.

---

home/templates/home/home_page.html
theme/static_src/src/djangonaut-space.css

I updated the homepage to better style the web-ring
* the container of the links (sessions, events..) is bigger
* the webring is resized to fit better inside the footer
* the black background is moved to fit the entire page
This is how the homepage looks now
This is how the footer looks on mobile

Styled webring

---

home/templates/home/home_page.html
indymeet/templates/includes/footer.html
indymeet/templates/includes/nav.html

Created "Donate" button that links here: https://opencollective.com/djangonaut-space
The button is added on:
* homepage
* in the footer
The screenshots also show what the button would look like in the navigation bar.

Created donate button

---

indymeet/templates/includes/resend_confirmation_email_button.html
indymeet/templates/registration/profile.html

This does several things to improve the styles and appearance of the application
- Removes CDN version of tailwind (this was reseting styles unexpectedly and the source of many headaches)
- Fixes the excerpt rendering as text rather than html
- Adjusts the styles and colors of buttons to be standard `class="action-button"` for the standard purple button now
- Links now appear as links with underlines (this is inline with accessibility standards for navigational elements)
- Made the create survey wider
References #500, #501

Style fix ups

---

.claude/shared.md
.github/dependabot.yml
.github/workflows/production.yml
.github/workflows/staging.yml
.github/workflows/tests.yml
.github/workflows/zizmor.yml

This switches to using hashes for the versions. This is a little more difficult to maintain, but dependabot will catch when there's a new version and Claude can more easily update the files.

Utilize Zizmor for GitHub Action security hardening
