djangonaut-space/wagtail-indymeet

home/static/css/welcome_page.css
home/templates/home/includes/event_card.html
home/templates/home/includes/event_team_member.html
home/templates/home/includes/events_past.html
home/templates/home/includes/events_upcoming.html
home/templates/home/includes/welcome_page.html
indymeet/static/css/indymeet.css
indymeet/templates/base.html
indymeet/templates/includes/footer.html
indymeet/templates/includes/nav.html
requirements/requirements.txt

small tweaks for style.
We can keep this branch open. If you're fine with the changes then we can merge in these small tweaks.

38 UI base styles

---

indymeet/templates/content_base.html
indymeet/templates/registration/login.html
indymeet/templates/registration/password_reset_complete.html
indymeet/templates/registration/password_reset_confirm.html
indymeet/templates/registration/password_reset_done.html
indymeet/templates/registration/password_reset_form.html

add custom formatted password reset templates

---

indymeet/templates/base.html
indymeet/templates/base_landing.html

Add plausible integration

---

home/templates/home/event_detail.html
home/templates/home/includes/session_card.html
home/templates/home/prerelease/session_detail.html

This makes the session and event pages easier to read.

Fix home templates

---

home/templates/home/calendar.html
home/templates/home/event_detail.html
home/templates/home/includes/event_card.html
home/templates/home/includes/session_card.html
home/templates/home/prerelease/event_detail.html
home/templates/home/prerelease/session_detail.html

I changed the date format everywhere according what was said in the discord
Preview examples:

Update date format to 'M d, Y'

---

home/models.py
home/templates/home/home_page.html
home/tests/test_models.py

I think as we want to have people sign up via the website in future, we can stop advertising it there for now. 
Small bug that we closed the applications on our website a day early, should fix this too. 🐛 
Don't worry about the event images 👍

Closing applications tweaks

---

home/static/css/blog.css
home/static/css/styles.css
indymeet/templates/blocks/heading.html
indymeet/templates/blocks/quote-left-image.html
indymeet/templates/blocks/text-image-heading.html
indymeet/templates/django_social_share/templatetags/post_to_facebook.html
indymeet/templates/django_social_share/templatetags/post_to_twitter.html
indymeet/templates/includes/breadcrumbs.html
indymeet/templates/puput/tags/post_to_linkedin.html

Closes #158 
Some improvements :
- add dynamic breadcumbs
- review accessibility of share on social medias icons
- add blog stylesheet and add some changes
Currently look like this (Unfinished) :
Detail article page

Improvements

---

.github/workflows/tests.yml
indymeet/settings/base.py
indymeet/settings/production.py

Reverts some changes from PR #137

Revert test GitHub action changes

---

home/templates/home/home_page.html
indymeet/templates/includes/nav.html

This means we're going to need a comms page in wagtail.

Add blog link to the pages.

---

home/templates/home/home_page.html

Deploy to production

---

indymeet/templates/puput/base.html

Production release - Use grid for the blog page.

---

accounts/forms.py
home/templates/home/home_page.html
indymeet/templates/includes/footer.html
indymeet/templates/includes/nav.html

Update the linked GitHub repository for documentation.

---

.env.template.local
.github/workflows/develop_djangonaut_space.yml
.github/workflows/main_djangonaut-space.yml
.github/workflows/tests.yml
README.md
accounts/forms.py
accounts/management/commands/create_playwright_user.py
accounts/management/commands/tests/test_create_playwright_user.py
accounts/tests.py
home/models.py
home/templates/home/home_page.html
indymeet/templates/includes/footer.html
indymeet/templates/includes/nav.html
requirements/requirements-dev.txt
requirements/requirements-test.in
requirements/requirements-test.txt
scripts/local.sh
setup.cfg
tests/__init__.py
tests/conftest.py
tests/test_end_to_end.py

PRs:
- https://github.com/djangonaut-space/wagtail-indymeet/pull/213
- https://github.com/djangonaut-space/wagtail-indymeet/pull/192
- https://github.com/djangonaut-space/wagtail-indymeet/pull/218
- https://github.com/djangonaut-space/wagtail-indymeet/pull/222
- https://github.com/djangonaut-space/wagtail-indymeet/pull/211
- https://github.com/djangonaut-space/wagtail-indymeet/pull/223

Production Deployment - fix links, add playwright test, small updates.

---

.github/workflows/develop_djangonaut_space.yml
.github/workflows/main_djangonaut-space.yml

- https://github.com/djangonaut-space/wagtail-indymeet/pull/212
We also had an update and a revert.

Production Deployment - bump azure/webapps-deploy from 2 to 3.

---

package.json
theme/static_src/package-lock.json
theme/static_src/package.json

https://github.com/djangonaut-space/wagtail-indymeet/issues/226

Upgrade to node 20.11.0.

---

home/templates/home/home_page.html

| Before| After|
|--------|--------|
| ![djangonaut space-a11y-codespaces-2024-01-19 000531](https://github.com/djangonaut-space/wagtail-indymeet/assets/44526468/25999524-d0cb-40a5-941c-1ce3e8e5d246) | ![djangonaut space-a11y-insights-fixed-codespaces](https://github.com/djangonaut-space/wagtail-indymeet/assets/44526468/0fc7e946-ba4e-4e0b-a8c3-be9a8322a616) |
| ![djangonaut space-a11y-codespaces-2024-01-19 000531-2](https://github.com/djangonaut-space/wagtail-indymeet/assets/44526468/7cc749b4-b028-4edd-9d72-81653d04bf09) | ![djangonaut space-a11y-fixed-codespaces-devtool](https://github.com/djangonaut-space/wagtail-indymeet/assets/44526468/f1d9a9ed-8a1f-46ea-b9a3-7b1fdd21e97c) |

[A11y] Fix issue aria-allowed-attr rule

---

theme/static_src/package-lock.json
theme/static_src/package.json

This prevents a person from running manage.py tailwind install and updating the dependencies for a different version of node than Azure can support.

Pin node version in package.json

---

.github/workflows/develop_djangonaut_space.yml
.github/workflows/main_djangonaut-space.yml

Reverts a node change to utilize the theme's package.json version of node.

Upgrade to app service build version 3.

---

.github/workflows/develop_djangonaut_space.yml
package-lock.json
package.json

I think this process could work, but I'd need to see what files are actually being uploaded, but I'm not sure how to do that.

Revert js build process

---

package-lock.json
package.json
theme/static_src/package-lock.json
theme/static_src/package.json

The error from oryx indicates that 20.9.0 is available, so let's give that a try.

Update node version to 20.9.0

---

scripts/postbuild.sh
scripts/startup.sh
supervisord.conf

Attempt to install supervisor during build

---

scripts/startup.sh
supervisord.conf

It was failing to start up causing the whole server to not load.

Add a supervisord section to supervisord.conf

---

requirements/requirements.in
requirements/requirements.txt
scripts/startup.sh

Installing things via the startup command causing conflicts from the apt lockfile.

Attempt to install supervisor via pip

---

accounts/factories.py
accounts/tests/test_activate_view.py
accounts/tests/test_profile_view.py
accounts/tests/test_unsubscribe_view.py
home/factories.py
home/tests/test_event_views.py
home/tests/test_models.py
home/tests/test_session_views.py
requirements/requirements-test.in
requirements/requirements-test.txt

Closes https://github.com/djangonaut-space/wagtail-indymeet/issues/275

Add Factory boy for tests.

---

home/management/commands/applications_open_email.py
home/models.py
home/tests/test_applications_open_email.py
indymeet/templates/emails/application_open.html
indymeet/templates/emails/application_open.txt
indymeet/templates/emails/base.html
indymeet/templates/emails/email_confirmation.html

(need to set up the cron job and generally agree this is wanted)

Add daily management command to send notification email when applications open.

---

.env.template
.env.template.local
.github/workflows/develop_djangonaut_space.yml
.github/workflows/main_djangonaut-space.yml
.github/workflows/tests.yml
indymeet/settings/base.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt
scripts/postbuild.sh

This reduces the number of environment variables we need for database connections. This will make environment configuration easier.
Closes #281

Switch to using DATABASE_URL for db connections.

---

indymeet/settings/base.py
indymeet/settings/production.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt
supervisord.conf

This will send emails out on a queue process using supervisord and postgres' listen/notify. Emails should go out every 30s by default.

Install and use django-mailer

---

accounts/forms.py
accounts/tests/test_profile_view.py
accounts/urls.py
accounts/views.py
indymeet/templates/registration/profile.html
indymeet/templates/registration/update_user.html

Adds a way to update your profile.
Need to update the email confirmation to be more generic but basics are here.

Add profile/user update page.

---

theme/static_src/src/djangonaut-space.css

Fixes https://github.com/djangonaut-space/wagtail-indymeet/issues/338.

Remove an unused !important that causes an error

---

accounts/forms.py
accounts/tests/test_signup_view.py
indymeet/settings/base.py
indymeet/settings/dev.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt

Dependabot was trying this, but its a bit complicated for that process, so here is version 4 with the new namespace.

chore: Upgrade to django-recaptcha 4

---

.git-blame-ignore-revs

Relates to: https://github.com/djangonaut-space/wagtail-indymeet/pull/343.

Git Blame ignore PR 343 pre-commit fixes

---

home/apps.py
indymeet/settings/base.py

https://docs.wagtail.org/en/latest/advanced_topics/performance.html#image-attributes

Lazy load wagtail images.

---

accounts/tests/test_auth_password_views.py
indymeet/templates/emails/base.html
indymeet/templates/includes/nav.html
indymeet/templates/registration/password_change_done.html
indymeet/templates/registration/password_change_form.html
indymeet/templates/registration/password_reset_email.html

Fixes https://github.com/djangonaut-space/wagtail-indymeet/issues/336

Added password change views and basic tests.

---

accounts/tests/test_resend_confirmation_email.py
accounts/tests/test_signup_view.py
accounts/urls.py
accounts/views.py
home/templates/home/includes/email_confirmed_warning.html
indymeet/templates/includes/messages.html
indymeet/templates/includes/resend_confirmation_email_button.html
indymeet/templates/registration/profile.html

Fixes https://github.com/djangonaut-space/wagtail-indymeet/issues/337

Add resend email confirmation flow.

---

indymeet/settings/base.py
indymeet/settings/dev.py
indymeet/settings/production.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt
supervisord.conf

feat: Add django-post_office for mail queueing

---

home/forms.py
home/managers.py
home/templates/home/includes/session_apply_btn.html
home/templates/home/surveys/form.html
home/tests/test_session_views.py
home/tests/test_user_survey_response_form_views.py
home/urls.py
home/views.py
indymeet/templates/forms/form.html

Fixes https://github.com/djangonaut-space/wagtail-indymeet/issues/353

Add a user survey response view.

---

README.md

Inside documentation now there are instructions to install pre-commit
* #310

chore: Update pre-commit instructions

---

home/templates/home/prerelease/session_list.html
home/views.py

I used the method of Session model `is_accepting_applications` to check if a session is open for the application.  Is it better to check the end of the `end_date` which is the end of the 8-week program? 
* #245

Feature: placeholder for sessions

---

indymeet/settings/base.py
indymeet/settings/dev.py
indymeet/settings/production.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt
supervisord.conf

This reverts commit aeae55a05b23db681b9da5c55c1c103fc0cba6d0.
Re-opens #312

Revert "feat: Add django-post_office for mail queueing (#359)"

---

home/templates/home/home_page.html

Added YouTube icon to the footer of landing page.

---

home/templates/home/home_page.html
indymeet/templates/base_landing.html
theme/static_src/src/djangonaut-space.css

I adjusted the custom CSS classes to get a **sticky footer**  and to use breakpoints in the body. 
I will attach some screenshots for reference

Fixed the responsiveness of the landing page

---

home/templates/home/home_page.html
theme/static/README

See: https://djangowebring.com

Add the site to the django webring.

---

home/templates/home/home_page.html
theme/static/README

Production Release - 2025-04-02

---

home/admin.py

Add basic analytics and tooling for surveys.
